"""Add confirm and avatar to model

Revision ID: 228a500a00b1
Revises: 686c18c9a8c9
Create Date: 2025-09-19 23:20:09.695482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "228a500a00b1"
down_revision: Union[str, Sequence[str], None] = "686c18c9a8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("confirmed", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET confirmed = TRUE WHERE confirmed IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
