NAME_MAX_LENGTH = 30
NAME_MIN_LENGTH = 2
EMAIL_MAX_LENGTH = 50
EMAIL_MIN_LENGTH = 5
PHONE_MAX_LENGTH = 15
PHONE_MIN_LENGTH = 10

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 30
USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 20
